[sdl]
autolock=false
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=surface
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-jsdos.map
usescancodes=true
vsync=false

[dosbox]
machine=svga_s3
language=
captures=capture
memsize=16

[cpu]
core=auto
cputype=auto
cycles=max
cycleup=10
cycledown=20

[render]
frameskip=0
aspect=false
scaler=none

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[speaker]
pcspeaker=true
pcrate=44100
tandy=auto
tandyrate=44100
disney=true

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[autoexec]
echo off
mount c .
c:
CITY.COM
